zsh: rename option syntax-highlighting
mayflower/nixpkgs pull request #21
Opened 2017-05-11 10:34 UTC by WilliButz

rename zsh-option "syntax-highlighting" -> "syntaxHighlighting"

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-11 12:18 UTC, Ma27 requested changes

2017-05-11 12:18 UTC, Ma27 commented on nixos/modules/rename.nix
> +    (mkRenamedOptionModule [ "programs" "zsh" "syntax-highlighting" "highlighters" ] [ "programs" "zsh" "syntaxHighlighting" "highlighters" ])
you have to update the `programs.zsh.syntax-highlighting.patterns` option as well...

2017-05-11 12:19 UTC, Ma27 commented
as I'm the author of this module: do we have any **consistent** style guide which describes the notation of module names? I've seen several modules in the `module-list` using dash and underscore notation, so it seems as camelCase is not the only thing in use.

2017-05-11 16:08 UTC, WilliButz commented on nixos/modules/rename.nix
> +    (mkRenamedOptionModule [ "programs" "zsh" "syntax-highlighting" "highlighters" ] [ "programs" "zsh" "syntaxHighlighting" "highlighters" ])
I obviously missed that :+1:

2017-05-11 16:08 UTC, fpletz approved these changes

2017-05-11 16:13 UTC, WilliButz commented
@Ma27 I don't know of any consistent style guide. My intention was to make the zsh options more similar.
Most of them are `enableSomeOption` and I thought why is not `enableSyntaxHighlighting`.

When I saw that there are more syntax-related options than just `enable`, I renamed it to something as close to the others as possible. :)

2017-05-11 16:13 UTC, fpletz commented
I didn't find any [documentation](https://nixos.org/nixos/manual/index.html#sec-writing-modules) on the case of NixOS option names but most core options (not regarding services/programs) seem to be camel-case.

2017-05-11 16:14 UTC, fpletz commented
@Ma27 If that's okay with you, I would merge this and push to upstream.

2017-05-11 16:48 UTC, groxxda commented
http://nixos.org/nixpkgs/manual/#sec-syntax :
> Use lowerCamelCase for variable names [...]

2017-05-11 16:58 UTC, Ma27 approved these changes

2017-05-11 17:00 UTC, Ma27 commented
@groxxda thanks for pointing that out.

@fpletz @WilliButz I'm fine with that. When I built that some weeks ago I was unsure which notation to take, so I decided to stay consistent with the package name.
However please keep in mind that `oh-my-zsh` might be renamed to `ohMyZsh` as well in that case.

2017-05-11 17:03 UTC, merged

2017-05-17 18:51 UTC, Ma27 commented
btw is it planned to merge this change back to upstream? Just asking because this is yet another diverge from upstream, but not that controversial IMHO.

2017-05-17 19:12 UTC, WilliButz commented
I'd like to see it upstream as well but it's not up to me to make this decision :)

2017-05-20 23:28 UTC, fpletz commented
Pushed upstream: https://github.com/NixOS/nixpkgs/commit/4e4f7a2f6684bae3ed156a2134edf99ccfa55cff