go: add dependencies for go get
mayflower/nixpkgs pull request #22
Opened 2017-05-11 15:55 UTC by WilliButz

###### Motivation for this change

`go get` expects git, subversion, mercurial and bazaar to be in `$PATH` when
needed. 
(https://github.com/golang/go/wiki/GoGetTools)

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Tested using `nix-shell -I nixpkgs=/path/to/local/nixpkgs -p go --pure`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-11 16:16 UTC, fpletz requested changes

2017-05-11 16:16 UTC, fpletz commented on pkgs/development/compilers/go/1.8.nix
> +      --prefix PATH ":" "${bazaar}/bin"
Please use `lib.makeBinPath` like

    --prefix PATH ":" "${makeBinPath [ git subversion mercurial bazaar ]}"

2017-05-11 16:29 UTC, WilliButz commented
@fpletz done :+1:

2017-05-11 16:53 UTC, fpletz approved these changes

2017-05-15 21:32 UTC, WilliButz commented
@fpletz ping :)

2017-05-17 13:46 UTC, merged

2017-05-20 23:23 UTC, fpletz commented
Pushed upstream: https://github.com/NixOS/nixpkgs/commit/458895db332d394bfadc05404a020ea0b4b1ee7f