prometheus alertmanager module
mayflower/nixpkgs pull request #7
Opened 2016-09-17 16:46 UTC by 0ida

###### Motivation for this change
Get Prometheus Alertmanager running in NixOS

###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [X] Tested in NixOS container
---

2016-09-17 18:47 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    	    Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal].
`types.enum [ "debug" "info" ... ]`

2016-09-17 18:48 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    	    The URL under which Alertmanager is externally reachable (for example, if Alertmanager is served via a reverse proxy).
Indentation

2016-09-17 18:50 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +          Port to listen on for the web interface and API. (default "9093")
Default ist schon im Attribut `default` vorgegeben, kann also aus der Beschreibung raus

2016-09-17 18:51 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    networking.firewall.allowedTCPPorts = [ cfg.port ];
Zumindest upstream soll die Firewall nicht automatisch geöffnet werde

2016-09-17 18:56 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +          Username under which Alertmanager shall be run.
User name

2016-09-17 19:00 UTC, groxxda requested changes
ich fänd es schöner statt "" wirklich null zu verwenden, d. h. `type = types.nullOr types.str`, `default = null` und eben `var != null`
Für die Konfiguration gibt's glaub ich auch einen Typen (`lines` oder so).

2016-09-17 21:35 UTC, 0ida commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    networking.firewall.allowedTCPPorts = [ cfg.port ];
Wird sie auch nicht. :D Aber hast natürlich recht, hab's konfigurierbar gemacht.

2016-09-17 22:14 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
>      	    Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal].
Hier noch die Werte aus der Beschreibung raus

2016-09-17 22:15 UTC, groxxda approved these changes
Achte auf die Arbeitszeiten :stuck_out_tongue_winking_eye:

2016-09-18 11:00 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    services.alertmanager = {
`services.alertmanager` -> `services.prometheus.alertmanager`

2016-09-18 11:01 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +  cfg = config.services.alertmanager;
`config.services.alertmanager` -> `config.services.prometheus.alertmanager`

2016-09-18 11:01 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +        default = "root";
Please don't use root as default.

2016-09-18 11:02 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +        type = types.str;
You could also use a nix attrset and write that as JSON (JSON is a subset of YAML)

2016-09-18 11:06 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +    networking.firewall = mkIf cfg.openFirewall {
`networking.firewall.allowedTCPPorts = optional cfg.openFirewall cfg.webListenPort;`

2016-09-18 11:07 UTC, globin commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +      webListenAddress = mkOption {
I'd prefer `listenAddress` and `port` to keep it consistent with other services.

2016-09-18 11:49 UTC, fpletz commented on nixos/modules/services/monitoring/prometheus/alertmanager.nix
> +        default = "root";
nobody should be fine.

2016-09-19 14:10 UTC, groxxda approved these changes

2016-09-19 16:09 UTC, merged