added options for prometheus alertmanager
mayflower/nixpkgs pull request #8
Opened 2016-09-17 17:28 UTC by 0ida

###### Motivation for this change
Additional options for Prometheus so it can be connected with Prometheus Alertmanager.

###### Things done
- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
---

2016-09-17 18:43 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/default.nix
> +        type = types.str;
```
type = types.listOf types.str;
default = [];
description = ''
  List of ...
''
```

2016-09-17 18:44 UTC, groxxda commented on nixos/modules/services/monitoring/prometheus/default.nix
> +    (optionalString (cfg.alertmanagerURL != "") "-alertmanager.url=${cfg.alertmanagerURL}")
`cfg.alertmanagerURL != []`

2016-09-17 18:45 UTC, groxxda requested changes
Upstreamen nicht vergessen ^^

2016-09-17 21:26 UTC, groxxda approved these changes

2016-09-18 11:08 UTC, globin approved these changes
LGTM

2016-09-19 16:09 UTC, merged